名称：构建 Android APK: Build Android APK
在：:
  推送：:
    分支：[ 主 ]: [ main ]

职位：:
  构建：:
    运行环境: ubuntu-latest: ubuntu-latest
    步骤：:
      - 名称：结账代码name: Checkout code
        使用：actions/checkout@v4: actions/checkout@v4
        使用：:
          # git自动统一换行，替代dos2unix工具# git自动统一换行，替代dos2unix工具
          core.autocrlf: 输入: input

      - 名称：设置 JDK 17name: Set up JDK 17
        使用：actions/setup-java@v5: actions/setup-java@v5
        使用：:
          java-version: '17': '17'
          发行版：'temurin': 'temurin'

      - 名称：设置 Android SDKname: Setup Android SDK
        使用：android-actions/setup-android@v3: android-actions/setup-android@v3

      - 名称：缓存 Gradlename: Cache Gradle
        使用：actions/cache@v4: actions/cache@v4
        使用：:
          路径: |: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('SuperAI-Android/**/*.gradle*') }}: ${{ runner.os }}-gradle-${{ hashFiles('SuperAI-Android/**/*.gradle*') }}
          恢复密钥：|: |
            ${{ runner.os }}-gradle-

      - 名称：修复 gradlew 权限name: Fix gradlew permission
        运行：chmod +x SuperAI-Android/gradlew: chmod +x SuperAI-Android/gradlew

      -      - name: Build Debug APK
        working-directory: ./SuperAI‑Android
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
          保留天数: 7: 7
